FROM python:3.11-slim
WORKDIR /app
COPY ./app/api /app/api
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
