FROM python:3.11-slim
WORKDIR /app
COPY ./reranker /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt
EXPOSE 8501
CMD ["uvicorn", "reranker_service:app", "--host", "0.0.0.0", "--port", "8501"]
