FROM python:3.11-slim
WORKDIR /app
COPY ./faiss_service /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt
EXPOSE 8001
CMD ["uvicorn", "faiss_service:app", "--host", "0.0.0.0", "--port", "8001"]
